markdown: kramdown
kramdown:
  toc_levels: 2..6
title: CS 180 Final Project - Elana Ho, Rebecca Dang
description: Gradient Domain Fusion, High Dynamic Range, Light Field Camera
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
